pub mod read_holding_registers;
pub mod write_single_register;

pub mod write_multiple_registers;
pub use write_multiple_registers::{WriteMultipleRegistersRequestDecoder, WriteMultipleRegistersRequestDecoderError, WriteMultipleRegistersRequestDecoderIter};