mod read_input_registers;
pub use read_input_registers::{ReadInputRegistersRequestEncoder, ReadInputRegistersRequestEncodeError, ReadInputRegistersRequestEncodeExceptionError};

mod write_single_register;